const axios = require('axios');
const crypto = require("crypto");

const url = 'https://oddsjam.com/api/backend/arbitrage';
const DISCORD_DEBUG_URL = 'https://discord.com/api/webhooks/1296059738638909470/BgFtlUG7m1jM6vViHsQZwVXRzpSkz0AcFLL-ZwlZUWswWG3oElEuitr6mJ_Dtd3oopdx';

function generateSignature() {
    const secretKey = "-YlucqCFXFkUKkVF+NR0==Fg34W7<WHH";
    
    const timestamp = Math.floor(Date.now() / 1000).toString();
    
    const hmac = crypto.createHmac('sha256', secretKey);
    hmac.update(timestamp);
    
    const signature = hmac.digest('base64');
    
    return signature;
}

// Function to send an embedded message to Discord
async function sendDiscordMessage(color, title, description) {
    const currentTime = new Date().toLocaleString(); // Get current time in local string format

    const embed = {
        embeds: [{
            title: title,
            description: description,
            color: color,
            footer: {
                text: `Sent at ${currentTime}`,  // Include time in the footer
            }
        }]
    };

    try {
        await axios.post(DISCORD_DEBUG_URL, embed, {
            headers: {
                'Content-Type': 'application/json'
            }
        });
    } catch (error) {
        console.error("Error sending Discord message:", error);
    }
}


async function processAllPages(accessToken) {
    let allData = [];
    let currentPage = 1;
    let hasMorePages = true;

    while (hasMorePages) {
        const payload = {
            granular_markets: [
                "2nd Half Correct Score",
                "2nd Half Double Chance",
                "Race To 20 Points",
                "1st Half Player Passing Yards",
                "Race To 5 Points",
                "Asian Total Goals",
                "Double Chance",
                "Last Team To Score",
                "1st Period Player Saves",
                "Race To 30 Points",
                "2nd Half Moneyline",
                "Race To 40 Points",
                "2nd Half Asian Team Total",
                "Race To 50 Points",
                "Race to 60 Points",
                "1st 3 Innings Moneyline",
                "1st 3 Quarters Moneyline 3-Way",
                "1st 9 Innings Moneyline 3-Way",
                "1st Half Anytime Touchdown Scorer",
                "1st Map Team Total",
                "1st Map Total Rounds Odd/Even",
                "2nd Half Moneyline 3-Way Reg Time",
                "2nd Half Asian Total Corners",
                "Moneyline",
                "Total Points Odd/Even",
                "2nd Half Asian Total Goals",
                "2nd Half Player Points",
                "2nd Half Race To 100 Points",
                "2nd Half Race To 10 Points",
                "2nd Half Race To 15 Points",
                "2nd Half Race To 20 Points",
                "2nd Half Total Behinds",
                "2nd Half Total Field Goals",
                "2nd Half Goal Spread",
                "2nd Half Point Spread",
                "2nd Half Total Corners",
                "Race To 25 Points",
                "Correct Score",
                "Player Crosses",
                "Goal Both Halves",
                "Player Dribble Attempts",
                "Asian Handicap Cards",
                "Team Total Cards",
                "Asian Team Total",
                "Race To 15 Points",
                "Asian Handicap",
                "1st Half Player Fantasy Score (SportsQuack)",
                "1st Half Player Free Throws Made",
                "2nd Half Total Goals",
                "1st Half Player Goals",
                "1st Half Player Made Threes",
                "1st Half Player Points",
                "1st Half Player Points + Rebounds + Assists",
                "1st Half Asian Team Total",
                "1st Half Race To 100 Points",
                "1st Half Race To 10 Points",
                "1st Half Race To 15 Points",
                "1st Half Race To 5 Points",
                "1st Half Race To 80 Points",
                "1st Half Race To 85 Points",
                "2nd Half Total Points Reg Time",
                "1st Half Player Fantasy Score (PrizePicks)",
                "2nd Half Total Touchdowns",
                "1st Half Asian Total Goals",
                "1st Half Asian Total Corners",
                "2nd Inning Moneyline",
                "1st Half Player Assists",
                "1st Half Player Dunks",
                "2nd Inning Moneyline 3-Way",
                "1st Half Asian Handicap Corners",
                "2nd Inning Player Earned Runs",
                "1st Half Player Fantasy Score",
                "1st Half Player Fantasy Score (SportsBattle)",
                "1st Half Player Shots On Target",
                "2nd Inning Player Hits Allowed",
                "2nd Inning Player Pitches Thrown",
                "2nd Map Asian Handicap",
                "2nd Map Moneyline",
                "2nd Map Player Assists",
                "1st Half Moneyline 3-Way",
                "2nd Half Total Points",
                "2nd Half Total Points Odd/Even",
                "1st 3 Maps Player Headshots",
                "1st 3 Maps Player Kills",
                "1st 3 Maps Player Penta Kills",
                "1st Half Total Goals",
                "1st Half Asian Handicap",
                "1st 3 Maps Player Quadra Kills",
                "1st Half Team Total",
                "1st Half Total Points",
                "1st 2 Maps Player Kills (Combo)",
                "1st 2 Maps Player Penta Kills",
                "1st 2 Maps Player Quadra Kills",
                "1st 2 Maps Player Triple Kills",
                "1st 3 Innings Moneyline 3-Way",
                "1st 3 Maps Player Triple Kills",
                "1st 3 Innings Player Earned Runs",
                "1st 3 Innings Player Strikeouts",
                "1st 3 Innings Run Line",
                "1st 3 Innings Team Total",
                "1st 3 Innings To Score",
                "1st 3 Innings Total Hits",
                "1st 3 Innings Total Runs",
                "1st 3 Innings Total Runs Odd/Even",
                "1st 3 Maps Player Assists",
                "1st 3 Maps Player Creep Score",
                "1st 3 Maps Player Deaths",
                "1st 3 Maps Player Double Kills",
                "1st 3 Quarters Moneyline",
                "1st Half Player Minutes Played",
                "1st Half Race To 90 Points",
                "1st Half Total Hits",
                "1st Half Both Teams To Score",
                "1st 7 Innings Run Line",
                "1st Half Draw No Bet",
                "1st 7 Innings Team Total",
                "1st 5 Minutes Total Goals",
                "2nd Half Asian Handicap",
                "1st Quarter Total Points Odd/Even",
                "1st 3 Quarters Point Spread",
                "1st 3 Quarters Total Points",
                "1st 4 Maps Player Demos",
                "1st 7 Innings To Score",
                "1st 7 Innings Total Hits",
                "1st 4 Maps Player Goals",
                "1st 4 Maps Player Saves",
                "1st 5 Innings Moneyline 3-Way",
                "1st 7 Innings Total Runs",
                "1st Half Goal Spread",
                "1st 7 Innings Total Runs Odd/Even",
                "1st 8 Innings Moneyline 3-Way",
                "1st 8 Minutes Total Goals",
                "1st 6 Minutes Player Points",
                "2nd Half Asian Handicap Corners",
                "1st 7 Innings Moneyline",
                "1st 7 Innings Moneyline 3-Way",
                "1st Set Player Games Won",
                "1st Half Team Total Corners",
                "1st Half Team Total Touchdowns",
                "1st Half To Score",
                "1st Half Total Behinds",
                "1st Half Total Field Goals",
                "2nd Half Race To 25 Points",
                "2nd Half Race To 30 Points",
                "2nd Half Race To 35 Points",
                "2nd Half Race To 40 Points",
                "2nd Half Race To 45 Points",
                "1st Half Total Corners",
                "2nd Half Race To 50 Points",
                "1st Half Team Total Goals",
                "1st Half Race To 95 Points",
                "2nd Half Race To 55 Points",
                "1st Half Run Line",
                "1st Half Team Total Behinds",
                "1st Half Team Total Field Goals",
                "1st Half Total Cards",
                "2nd Half Race To 5 Points",
                "1st Half Team Clean Sheet",
                "2nd Half Team Clean Sheet",
                "2nd Half Race To 60 Points",
                "2nd Half Race To 65 Points",
                "2nd Half Race To 70 Points",
                "2nd Inning Team Total",
                "1st Half Total Runs",
                "1st Half Total Touchdowns",
                "1st Half Total Tries",
                "1st Inning Moneyline",
                "1st Inning Moneyline 3-Way",
                "1st Inning Player Earned Runs",
                "1st Inning Player Hits Allowed",
                "1st Period Moneyline",
                "2nd Inning Player Strikeouts",
                "1st Half Total Points Odd/Even",
                "1st Inning Player Pitches Thrown",
                "1st Period First Team To Score",
                "2nd Inning Run Line",
                "2nd Inning To Score",
                "2nd Inning Total Hits",
                "2nd Inning Total Runs",
                "2nd Inning Total Runs Odd/Even",
                "1st Inning Total Runs Odd/Even",
                "1st Inning Player Strikeouts",
                "1st Inning Run Line",
                "1st Inning Team Total",
                "1st Inning Team Total Hits",
                "1st Inning To Score",
                "1st Inning Total Hits",
                "1st Inning Total Runs",
                "1st Map Asian Handicap",
                "1st Map Handicap",
                "1st Map Moneyline",
                "1st Map Player Assists",
                "1st Map Player Creep Score",
                "1st Map Player Deaths",
                "2nd Map Player Creep Score",
                "1st Half Total Goals Odd/Even",
                "2nd Half Total Goals Odd/Even",
                "1st Half Double Chance",
                "1st Map Player Double Kills",
                "1st Map Player Fantasy Score (Underdog)",
                "1st Map Player Headshots",
                "1st Map Player Kills",
                "1st Map Player Penta Kills",
                "1st Map Player Quadra Kills",
                "2nd Map Player Deaths",
                "2nd Map Player Double Kills",
                "2nd Map Player Fantasy Score (Underdog)",
                "2nd Map Player Headshots",
                "2nd Map Player Kills",
                "2nd Map Player Penta Kills",
                "2nd Map Player Quadra Kills",
                "2nd Map Player Triple Kills",
                "2nd Map Round Handicap",
                "2nd Map Team Total",
                "2nd Map Total Bombs Defused",
                "2nd Map Total Kills",
                "2nd Map Total Kills Odd/Even",
                "1st Half Moneyline",
                "2nd Half Team Total",
                "2nd Map Total Rounds",
                "2nd Map Total Rounds Odd/Even",
                "2nd Map Team Destroy First Inhibitor",
                "2nd Map Team First Blood",
                "2nd Map Team First Elemental Dragon",
                "2nd Map Total Inhibitors Destroyed",
                "3rd Set Game 3 Winner",
                "1st Map Player Triple Kills",
                "1st Map Round Handicap",
                "1st Map Total Kills",
                "1st Map Total Kills Odd/Even",
                "1st Map Total Rounds",
                "1st Map Team Destroy First Inhibitor",
                "1st Map Team First Blood",
                "2nd Map Total Turrets Destroyed",
                "2nd Period Both Teams To Score",
                "2nd Period First Goal Scorer",
                "2nd Period First Team To Score",
                "2nd Period Last Goal Scorer",
                "2nd Period Moneyline",
                "3rd Set Game Spread",
                "1st Map Team First Elemental Dragon",
                "1st Map Total Inhibitors Destroyed",
                "1st Map Total Turrets Destroyed",
                "Eagles total points scored in 2nd half + OT",
                "1st Over Total Runs",
                "1st Period Both Teams To Score",
                "1st Period Correct Score",
                "1st Period Moneyline 3-Way",
                "1st Period Puck Line",
                "1st Quarter Player Assists",
                "1st Quarter Player Free Throws Made",
                "2nd Period Moneyline 3-Way",
                "2nd Period Player Saves",
                "2nd Period Player Shots On Goal",
                "2nd Period Puck Line",
                "Highest Scoring Half",
                "2nd Period Total Goals",
                "2nd Period Total Goals Odd/Even",
                "2nd Quarter First Goal Scorer",
                "2nd Period Team Total",
                "1st Quarter Moneyline 3-Way",
                "2nd Quarter Moneyline",
                "2nd Quarter Race To 15 Points",
                "2nd Quarter Race To 20 Points",
                "2nd Quarter Race To 25 Points",
                "2nd Quarter Race To 30 Points",
                "2nd Quarter Team Total",
                "1st Quarter Player Minutes",
                "1st Quarter Player Points",
                "1st Quarter Player Points + Rebounds + Assists",
                "1st Quarter Player Rebounds",
                "8th Inning Player Strikeouts",
                "1st Quarter Player Receiving Yards",
                "2nd Quarter Race To 35 Points",
                "2nd Quarter Race To 40 Points",
                "2nd Quarter Race To 45 Points",
                "2nd Quarter Race To 50 Points",
                "2nd Quarter Race To 5 Points",
                "2nd Quarter Team Total Behinds",
                "1st Quarter Race To 10 Points",
                "1st Quarter Point Spread",
                "1st Quarter Player Rushing Yards",
                "2nd Quarter Team Total Goals",
                "1st Quarter Race To 15 Points",
                "1st Quarter Race To 20 Points",
                "1st Quarter Race To 25 Points",
                "1st Quarter Race To 30 Points",
                "2nd Quarter Total Behinds",
                "2nd Quarter Total Goals",
                "Both Halves Goal Scored",
                "2nd Half Goal Scored",
                "1st Half Goal Scored",
                "1st Quarter Race To 45 Points",
                "1st Quarter Race To 50 Points",
                "1st Quarter Team Total",
                "1st Quarter Race To 5 Points",
                "1st Quarter Team Total Behinds",
                "1st Quarter Team Total Goals",
                "1st Quarter Team Total Touchdowns",
                "1st Quarter Total Behinds",
                "1st Round Moneyline",
                "1st Set Betting",
                "1st Set Correct Score",
                "1st Set Game 10 Winner",
                "2nd Quarter Total Points Odd/Even",
                "2nd Round Handicap",
                "2nd Round Moneyline",
                "2nd Set Betting",
                "2nd Set Game 3 Winner",
                "2nd Set Game 4 Winner",
                "1st Quarter Total Goals",
                "1st Quarter Total Points",
                "1st Round Handicap",
                "2nd Set Game 5 Winner",
                "2nd Set Game 6 Winner",
                "2nd Set Game 7 Winner",
                "2nd Set Game 8 Winner",
                "2nd Quarter Total Points",
                "2nd Set Game 9 Winner",
                "2nd Set Game Spread",
                "2nd Set Moneyline",
                "2nd Set Player Aces",
                "2nd Set Player Games Lost",
                "Race to 255 Points",
                "1st 3 Maps Player Kills (Combo)",
                "1st Half Race To 20 Points",
                "1st Half Race To 25 Points",
                "1st Half Race To 30 Points",
                "1st Half Race To 35 Points",
                "1st Half Race To 40 Points",
                "1st Half Race To 45 Points",
                "1st Half Race To 50 Points",
                "1st Half Race To 55 Points",
                "1st Quarter Double Chance",
                "1st Half Race To 60 Points",
                "1st Half Race To 65 Points",
                "1st Half Race To 70 Points",
                "1st Half Race To 75 Points",
                "1st Map Kills Handicap",
                "1st Map Team Total Kills",
                "1st Map Total Bombs Defused",
                "1st Quarter Race To 35 Points",
                "1st Quarter Race To 40 Points",
                "1st Set Game 11 Winner",
                "1st Set Game 12 Winner",
                "1st Set Game 1 Winner",
                "1st Set Game 2 Winner",
                "1st Set Game 3 Winner",
                "1st Set Game 4 Winner",
                "1st Set Game 5 Winner",
                "1st Set Game 6 Winner",
                "1st Set Game 7 Winner",
                "1st Set Game 8 Winner",
                "2nd Map Kills Handicap",
                "2nd Map Team Total Kills",
                "1st Period First Goal Scorer",
                "2nd Half Player Made Threes",
                "2nd Set Player Games Won",
                "2nd Set Total Games",
                "1st Period Player Goals",
                "2nd Set Total Games Odd/Even",
                "3rd Inning Moneyline",
                "3rd Inning Moneyline 3-Way",
                "3rd Inning Player Earned Runs",
                "3rd Inning Player Hits Allowed",
                "3rd Inning Player Pitches Thrown",
                "2nd Half Player Fantasy Score (PrizePicks)",
                "2nd Half Moneyline 3-Way",
                "3rd Inning Player Strikeouts",
                "Number of different Chiefs to score points",
                "2nd Half Both Teams To Score",
                "Chiefs total points scored in 2nd half + OT",
                "1st 3 Maps Player Fantasy Score (Underdog)",
                "1st Period Last Goal Scorer",
                "3rd Inning Run Line",
                "2nd Half Draw No Bet",
                "1st Period Player Shots On Goal",
                "3rd Inning To Score",
                "1st Set Game 9 Winner",
                "1st Set Game Spread",
                "1st Set Moneyline",
                "1st Set Player Aces",
                "1st Set Player Games Lost",
                "1st Set Total Games",
                "1st Set Total Games Odd/Even",
                "2nd Half Anytime Touchdown Scorer",
                "2nd Half Moneyline Reg Time",
                "2nd Half Player Assists",
                "2nd Half Player Goals",
                "3rd Inning Total Hits",
                "3rd Inning Total Runs",
                "3rd Inning Total Runs Odd/Even",
                "3rd Map Asian Handicap",
                "3rd Map Handicap",
                "3rd Map Kills Handicap",
                "3rd Map Moneyline",
                "2nd Half Race To 75 Points",
                "2nd Half Race To 80 Points",
                "2nd Half Race To 85 Points",
                "2nd Half Race To 90 Points",
                "2nd Half Race To 95 Points",
                "2nd Half Team Total Exact",
                "3rd Map Player Quadra Kills",
                "3rd Map Player Triple Kills",
                "3rd Map Team Total",
                "3rd Map Team Total Kills",
                "3rd Map Total Bombs Defused",
                "3rd Map Total Kills",
                "3rd Map Total Kills Odd/Even",
                "3rd Map Total Rounds",
                "3rd Map Total Rounds Odd/Even",
                "3rd Map Team Destroy First Inhibitor",
                "3rd Map Team First Blood",
                "3rd Map Team First Elemental Dragon",
                "3rd Map Total Inhibitors Destroyed",
                "3rd Map Total Turrets Destroyed",
                "3rd Period Both Teams To Score",
                "3rd Period First Goal Scorer",
                "3rd Period First Team To Score",
                "3rd Period Last Goal Scorer",
                "3rd Period Moneyline",
                "Number of different Eagles to score points",
                "3rd Period Moneyline 3-Way",
                "3rd Period Player Saves",
                "3rd Period Player Shots On Goal",
                "3rd Period Puck Line",
                "3rd Period Total Goals",
                "3rd Period Total Goals Odd/Even",
                "3rd Quarter First Goal Scorer",
                "3rd Quarter Player Points",
                "3rd Quarter Race To 10 Points",
                "3rd Quarter Race To 15 Points",
                "3rd Quarter Race To 20 Points",
                "3rd Quarter Race To 25 Points",
                "3rd Quarter Race To 30 Points",
                "3rd Quarter Race To 35 Points",
                "3rd Quarter Race To 40 Points",
                "3rd Quarter Race To 45 Points",
                "3rd Quarter Race To 50 Points",
                "3rd Quarter Race To 5 Points",
                "3rd Quarter Team Total Behinds",
                "3rd Quarter Team Total Goals",
                "3rd Quarter Total Behinds",
                "3rd Quarter Total Goals",
                "3rd Period Team Total",
                "3rd Quarter Moneyline",
                "3rd Quarter Point Spread",
                "3rd Quarter Moneyline 3-Way",
                "3rd Quarter Team Total",
                "3rd Quarter Total Points",
                "3rd Quarter Total Points Odd/Even",
                "2nd Quarter Moneyline 3-Way",
                "1st 2 Innings Moneyline 3-Way",
                "1st 4 Innings Moneyline 3-Way",
                "1st 6 Innings Moneyline 3-Way",
                "1st Half Team Total Hits",
                "1st Inning Most Hits 3-Way",
                "1st Inning Total Hits + Runs + Errors",
                "2nd Quarter Player Points",
                "2nd Quarter Race To 10 Points",
                "3rd Round Handicap",
                "3rd Round Moneyline",
                "3rd Set Betting",
                "3rd Set Player Games Won",
                "3rd Set Total Games",
                "3rd Set Total Games Odd/Even",
                "4th Inning Moneyline",
                "4th Inning Moneyline 3-Way",
                "4th Inning Player Earned Runs",
                "4th Inning Player Hits Allowed",
                "4th Inning Player Pitches Thrown",
                "4th Inning Player Strikeouts",
                "4th Inning Run Line",
                "4th Inning To Score",
                "4th Inning Total Hits",
                "4th Inning Total Runs",
                "4th Inning Total Runs Odd/Even",
                "4th Map Asian Handicap",
                "4th Map Handicap",
                "4th Map Kills Handicap",
                "4th Map Moneyline",
                "4th Map Player Assists",
                "4th Map Player Creep Score",
                "4th Map Player Deaths",
                "4th Map Player Double Kills",
                "4th Map Player Fantasy Score (Underdog)",
                "4th Map Player Headshots",
                "4th Map Player Kills",
                "4th Map Player Penta Kills",
                "4th Map Player Quadra Kills",
                "4th Map Player Triple Kills",
                "4th Map Round Handicap",
                "4th Map Team Total",
                "4th Map Team Total Kills",
                "4th Map Total Bombs Defused",
                "4th Map Total Kills",
                "4th Map Total Kills Odd/Even",
                "2nd Quarter Point Spread",
                "3rd Map Player Assists",
                "3rd Map Player Creep Score",
                "3rd Map Player Deaths",
                "3rd Map Player Double Kills",
                "3rd Map Player Fantasy Score (Underdog)",
                "3rd Map Player Headshots",
                "3rd Map Player Kills",
                "3rd Map Player Penta Kills",
                "3rd Map Round Handicap",
                "4th Map Total Rounds",
                "4th Map Total Rounds Odd/Even",
                "4th Quarter First Goal Scorer",
                "4th Quarter Player Points",
                "4th Quarter Race To 45 Points",
                "4th Quarter Race To 50 Points",
                "4th Quarter Race To 5 Points",
                "4th Quarter Team Total Behinds",
                "4th Quarter Team Total Goals",
                "4th Quarter Total Behinds",
                "4th Quarter Total Goals",
                "4th Quarter Total Points (incl OT)",
                "4th Round Handicap",
                "4th Round Moneyline",
                "4th Set Betting",
                "4th Set Game 10 Winner",
                "4th Set Game 11 Winner",
                "4th Set Game 12 Winner",
                "4th Set Game 1 Winner",
                "4th Set Game 2 Winner",
                "4th Set Game 3 Winner",
                "4th Set Game 4 Winner",
                "4th Set Game 5 Winner",
                "4th Set Game Spread",
                "4th Set Moneyline",
                "4th Set Player Aces",
                "4th Set Player Games Lost",
                "4th Set Player Games Won",
                "4th Set Total Games",
                "5th Inning Player Earned Runs",
                "5th Inning Player Hits Allowed",
                "5th Inning Player Pitches Thrown",
                "5th Inning Player Strikeouts",
                "5th Map Kills Handicap",
                "5th Map Player Assists",
                "5th Map Player Creep Score",
                "4th Quarter Moneyline 3-Way (incl OT)",
                "4th Quarter Moneyline (incl OT)",
                "4th Quarter Moneyline 3-Way",
                "4th Quarter Player Fantasy Score (PrizePicks)",
                "4th Quarter Team Total",
                "4th Quarter Total Points",
                "4th Quarter Total Points Odd/Even",
                "4th Quarter Moneyline",
                "3rd Set Game 10 Winner",
                "3rd Set Game 11 Winner",
                "3rd Set Game 12 Winner",
                "3rd Set Game 1 Winner",
                "3rd Set Game 2 Winner",
                "3rd Set Moneyline",
                "3rd Set Player Aces",
                "3rd Set Player Games Lost",
                "5th Map Player Deaths",
                "1st Half Total Corners Odd/Even",
                "5th Map Player Double Kills",
                "5th Map Player Fantasy Score (Underdog)",
                "5th Map Player Headshots",
                "5th Map Player Penta Kills",
                "5th Map Player Quadra Kills",
                "5th Map Player Triple Kills",
                "5th Map Team Total",
                "5th Map Team Total Kills",
                "5th Map Total Bombs Defused",
                "5th Map Total Kills",
                "5th Map Total Kills Odd/Even",
                "5th Map Total Rounds",
                "5th Map Total Rounds Odd/Even",
                "5th Set Betting",
                "5th Set Game 10 Winner",
                "5th Set Game 11 Winner",
                "5th Set Game 12 Winner",
                "5th Set Game 1 Winner",
                "5th Set Game 2 Winner",
                "5th Set Game 3 Winner",
                "5th Set Game 4 Winner",
                "5th Set Game 5 Winner",
                "5th Set Game 6 Winner",
                "5th Set Game 7 Winner",
                "5th Set Game 8 Winner",
                "5th Set Game 9 Winner",
                "5th Set Game Spread",
                "5th Set Moneyline",
                "5th Set Player Aces",
                "5th Set Player Games Lost",
                "5th Set Player Games Won",
                "5th Set Total Games",
                "5th Set Total Games Odd/Even",
                "6th Inning Moneyline",
                "6th Inning Moneyline 3-Way",
                "6th Inning Player Earned Runs",
                "6th Inning Player Hits Allowed",
                "6th Inning Player Pitches Thrown",
                "6th Inning Player Strikeouts",
                "6th Inning Run Line",
                "6th Inning To Score",
                "1st Half Team Total Cards",
                "2nd Half Team Total Cards",
                "1st Half Team Total Exact",
                "1st Half Correct Score",
                "1st Half Team Total Goals Odd/Even",
                "4th Quarter Point Spread",
                "2nd Half Team Total Goals Odd/Even",
                "1st Half Team Total Yellow Cards",
                "1st Half Total Yellow Cards",
                "2nd Half Team Total Yellow Cards",
                "2nd Half Total Corners Odd/Even",
                "2nd Half Total Yellow Cards",
                "4th Quarter Point Spread (incl OT)",
                "4th Quarter Race To 10 Points",
                "4th Quarter Race To 15 Points",
                "4th Quarter Race To 20 Points",
                "4th Quarter Race To 25 Points",
                "4th Quarter Race To 30 Points",
                "4th Quarter Race To 35 Points",
                "4th Quarter Race To 40 Points",
                "6th Inning Total Hits",
                "6th Inning Total Runs",
                "6th Inning Total Runs Odd/Even",
                "7th Inning Moneyline",
                "7th Inning Moneyline 3-Way",
                "7th Inning Player Earned Runs",
                "7th Inning Player Hits Allowed",
                "7th Inning Player Pitches Thrown",
                "7th Inning Total Runs Odd/Even",
                "8th Inning Moneyline",
                "4th Set Game 6 Winner",
                "4th Set Game 7 Winner",
                "4th Set Game 8 Winner",
                "4th Set Game 9 Winner",
                "8th Inning Moneyline 3-Way",
                "8th Inning Player Earned Runs",
                "8th Inning Player Hits Allowed",
                "8th Inning Player Pitches Thrown",
                "8th Inning Run Line",
                "8th Inning To Score",
                "8th Inning Total Hits",
                "8th Inning Total Runs",
                "8th Inning Total Runs Odd/Even",
                "9th Inning Moneyline",
                "9th Inning Moneyline 3-Way",
                "9th Inning Player Earned Runs",
                "9th Inning Player Hits Allowed",
                "9th Inning Player Pitches Thrown",
                "9th Inning Player Strikeouts",
                "9th Inning Run Line",
                "9th Inning To Score",
                "9th Inning Total Hits",
                "Asian Handicap Corners",
                "9th Inning Total Runs",
                "9th Inning Total Runs Odd/Even",
                "Anytime Goal Scorer By Header",
                "Anytime Goal Scorer Outside Box",
                "Anytime Touchdown Scorer",
                "First Team To Score",
                "First Goal Scorer",
                "Asian Map Handicap",
                "Asian Total Corners",
                "Last Goal Scorer",
                "Moneyline 3-Way",
                "First Basket",
                "First Basket Including FT",
                "First Goal Scorer Reg Time",
                "First Or Last Goal Scorer",
                "First Team Basket",
                "First Team To Score Field Goal",
                "First Touchdown Scorer",
                "Game Spread",
                "Go The Distance",
                "Handicap",
                "Highest Scoring Inning",
                "Goal Spread",
                "Last Touchdown Scorer",
                "Man Of The Match",
                "Map Handicap",
                "Method Of First Basket",
                "Method Of First Basket Including FT",
                "Method of Victory",
                "Both Teams To Score Reg Time",
                "Draw No Bet Reg Time",
                "Anytime Goal Scorer",
                "Longest Touchdown Yards",
                "7th Inning Player Strikeouts",
                "7th Inning Run Line",
                "7th Inning To Score",
                "7th Inning Total Hits",
                "7th Inning Total Runs",
                "Most Hits 3-Way",
                "No Runs First Inning",
                "Penalty Awarded",
                "Player Aces",
                "Player Aces + Double Faults",
                "Player Bases",
                "Player Batting Fantasy Score (Betr)",
                "Player Batting Fantasy Score (ParlayPlay)",
                "Player Batting Fantasy Score (PrizePicks)",
                "Player Batting Fantasy Score (SportsBattle)",
                "Player Batting Fantasy Score (SportsQuack)",
                "Player Batting Fantasy Score (Underdog)",
                "Player Batting Strikeouts",
                "Player Batting Walks",
                "Player Batting Walks (Combo)",
                "Player Birdies Streak",
                "Player Blocks",
                "Player Bogeys Or Better",
                "Player Bogeys Or Worse",
                "Player Break Points Won",
                "Player Chances Created",
                "Player Cumulative Par 5 Strokes",
                "Player Defensive Rebounds",
                "Player Deflections",
                "Player Disposals",
                "Player Double Faults",
                "Player Doubles",
                "Player Dunks",
                "Player Extra Points Made",
                "Player Fairways Hit",
                "Player Fantasy Score (Hotstreak)",
                "Player Fantasy Score (ParlayPlay)",
                "Player Fantasy Score (PrizePicks)",
                "Player Fantasy Score (Sleeper)",
                "Player Fantasy Score (SportsBattle)",
                "Player Fantasy Score (SportsQuack)",
                "Player Fantasy Score (Underdog)",
                "Player Fantasy Score (Underdog) (Combo)",
                "Player Field Goals Attempted",
                "Player Field Goals Made",
                "Player Field Goals Made (Combo)",
                "Player Field Goals Made In First 3 Attempts",
                "Player Field Goals Made In First 5 Attempts",
                "Player Clearances",
                "Player Birdies Or Better",
                "Player Defensive Interceptions",
                "Player Cards",
                "Player Assists",
                "Moneyline Reg Time",
                "Player Double Double",
                "Player Faceoffs Won",
                "Player Fantasy Score",
                "Player Blocked Shots",
                "Player Fantasy Score (Betr)",
                "Player Assists (Combo)",
                "Player Average Kills Per Map",
                "Player Field Goals Missed",
                "Player Fight Time Minutes",
                "Player Finishes",
                "Player First Downs",
                "Player First Rushing Attempt Yards",
                "Player First Serve Percentage",
                "Player First Touchdown Pass Yards",
                "Player Fouls Drawn",
                "Player Fours",
                "Player Free Throws Attempted",
                "Player Free Throws Made",
                "Player Games Lost",
                "Player Games Won",
                "Player Goals Allowed",
                "Player Goals (Combo)",
                "Player Goals Inside Box",
                "Player Hits + Runs + RBIs",
                "Player Hits + Runs + RBIs (Combo)",
                "Player Hits Allowed",
                "Player Home Runs",
                "Player Home Runs Yes/No",
                "Player Interceptions",
                "Player Interceptions (Combo)",
                "Player Kicking Points",
                "Player Kicking Points (Combo)",
                "Player Knockouts",
                "Player Longest Passing Completion",
                "Player Longest Reception",
                "Player Longest Rush",
                "Player Made Threes (Combo)",
                "Player Made Two Pointers",
                "Player Minutes Played",
                "Player Offensive Rebounds",
                "Player Offsides",
                "Player Outs",
                "Player Pars",
                "Player Pars Or Better",
                "Player Goals",
                "Player Passes",
                "Player Goals Against",
                "Player Passes Attempted",
                "Player Passes Attempted (Combo)",
                "Player Passes Completed",
                "Player Passing Completion Percentage",
                "Player Passing Completions",
                "Player Passing First Downs",
                "Player Passing Touchdowns",
                "Player Passing Touchdowns (Combo)",
                "Player Passing Yards",
                "Player Passing Yards (Combo)",
                "Player Personal Fouls",
                "Player Pitches Thrown",
                "Player Pitching Fantasy Score (Betr)",
                "Player Pitching Fantasy Score (PrizePicks)",
                "Player Pitching Fantasy Score (SportsBattle)",
                "Player Fouls",
                "Player Goals + Assists",
                "Player Passing Attempts",
                "Player Made Threes",
                "Player Goals Outside Box",
                "Player Greens In Regulation",
                "Player Saves",
                "Player Pitching Fantasy Score (SportsQuack)",
                "Player Pitching Fantasy Score (Underdog)",
                "Player Plus Minus",
                "Player Points + Assists",
                "Player Points + Rebounds",
                "Player Points (Combo)",
                "Player Punts",
                "Player RBIs",
                "Player Rebounds + Assists",
                "Player Rebounds (Combo)",
                "Player Receiving Targets",
                "Player Receiving Touchdowns",
                "Player Receiving Yards",
                "Player Receiving Yards After Catch",
                "Player Receiving Yards (Combo)",
                "Player Receptions",
                "Player Receptions (Combo)",
                "Player Runs",
                "Player Runs + RBIs",
                "Player Rushing + Receiving Yards",
                "Player Rushing + Receiving Yards (Combo)",
                "Player Rushing Attempts",
                "Player Rushing Yards",
                "Player Rushing Yards (Combo)",
                "Player Sacks",
                "Player Sacks (Combo)",
                "Player Sacks Taken",
                "Player Service Games Lost",
                "Player Sets Lost",
                "Player Sets Won",
                "Player Shots Attempted",
                "Player Shots Attempted (Combo)",
                "Player Shots Attempted Outside Box",
                "Player Shots (Combo)",
                "Player Shots On Goal + Blocked Shots",
                "Player Shots On Goal Reg Time",
                "Player Shots On Target (Combo)",
                "Player Singles",
                "Player Sixes",
                "Player Steals",
                "Player Steals + Blocks",
                "Player Stolen Bases",
                "Player Stolen Bases (Combo)",
                "Player Strikeouts",
                "Player Strikeouts (Combo)",
                "Player Submissions",
                "Player Tackles + Assists",
                "Player Tackles For Loss",
                "Player Shots On Target",
                "Player Saves (Combo)",
                "Player Tackles",
                "Player Shots On Goal",
                "Player Points + Rebounds + Assists",
                "Player Strokes",
                "Player Shots Assisted",
                "Player Rebounds",
                "Player Points",
                "Player Power Play Points",
                "Player Shots",
                "Player Hits",
                "Player Shots On Goal (Combo)",
                "Player Rushing Attempts (Combo)",
                "Player Rushing Touchdowns",
                "Player Takedowns",
                "Player Threes Attempted",
                "Player Threes Attempted (Combo)",
                "Player To Record Win",
                "Player Touchdowns",
                "Player Touchdowns (Combo)",
                "Player Triple Double",
                "Player Triples",
                "Player Turnovers",
                "Player Two Pointers Attempted",
                "Player Walks",
                "Player Wickets Taken",
                "Puck Line",
                "Puck Line Reg Time",
                "Race to 100 Points",
                "Race to 105 Points",
                "Race to 110 Points",
                "Race to 115 Points",
                "Race to 120 Points",
                "Race to 125 Points",
                "Race to 130 Points",
                "Race to 135 Points",
                "Race to 140 Points",
                "Race to 145 Points",
                "Race to 150 Points",
                "Race to 155 Points",
                "Player Time On Ice",
                "Race to 160 Points",
                "Race to 165 Points",
                "Race to 170 Points",
                "Player To Record Shutout",
                "Race to 210 Points",
                "Race to 215 Points",
                "Race to 220 Points",
                "Race to 225 Points",
                "Race to 230 Points",
                "Race to 235 Points",
                "Race to 240 Points",
                "Race to 245 Points",
                "Race to 250 Points",
                "Race To 10 Points",
                "Race to 260 Points",
                "Race to 265 Points",
                "Point Spread",
                "Race To 55 Points",
                "Race to 65 Points",
                "Race to 70 Points",
                "Race to 75 Points",
                "Race to 80 Points",
                "Race to 85 Points",
                "Race to 90 Points",
                "Race to 95 Points",
                "Round Betting",
                "Run Line",
                "Set Betting",
                "Player To Score Or Assist",
                "Second Goal Scorer",
                "Race to 175 Points",
                "Race to 180 Points",
                "Race to 185 Points",
                "Race to 190 Points",
                "Race to 195 Points",
                "Race to 200 Points",
                "Race to 205 Points",
                "Set Handicap",
                "Team Highest Scoring Inning 3-Way",
                "Team Top Batsman",
                "Team Top Bowler",
                "Team Total 1st Downs",
                "Team Total 3rd Down Conversions",
                "Set Spread",
                "Team Total Assists",
                "Team Total Behinds",
                "Team Total Blocks",
                "Total Goals",
                "Team Total Consecutive Points",
                "Team Total Fours",
                "Total Ducks",
                "Total Field Goals",
                "Total Fouls",
                "Total Fours",
                "Total Games",
                "Total Games Odd/Even",
                "Total Goals Odd/Even Reg Time",
                "Total Goals Reg Time",
                "Total Hits",
                "Total Hits + Runs + Errors",
                "Total Home Runs",
                "Total Home Runs Odd/Even",
                "Total Maps",
                "Total Passing Touchdowns",
                "Total Rounds",
                "Total Rounds Odd/Even",
                "Total Run Outs",
                "Total Runs",
                "Team Total",
                "Total Runs Odd/Even",
                "Total Rushing Touchdowns",
                "Total Sacks",
                "Total Sets",
                "Total Sets Exact",
                "Total Sixes",
                "Total Stumpings",
                "Total Touchdowns",
                "Team Total Field Goals",
                "Team To Win Both Halves",
                "Total Goals Odd/Even",
                "Total Double Faults",
                "Total Offsides",
                "Total Shots On Target",
                "Total Tries",
                "Total Points",
                "Team Clean Sheet",
                "Total Shots",
                "Team Total Fouls",
                "Total Punts",
                "Total Power Play Goals",
                "Team Total Corners",
                "Total Short Handed Goals",
                "Total Shots On Goal",
                "Team Total Points Odd/Even",
                "Team Total Shots On Target",
                "Team Total Shots",
                "Team Total Hits",
                "Team Total Home Runs",
                "Team Total Made Threes",
                "Team Total Passing Attempts",
                "Team Total Passing Touchdowns",
                "Team Total Sacks",
                "Team Total Odd/Even",
                "Team Total Steals",
                "Team Destroy First Inhibitor",
                "Team First Blood",
                "Team First Elemental Dragon",
                "Total Inhibitors Destroyed",
                "Total Turrets Destroyed",
                "To Win The Toss + Moneyline",
                "To Win To Nil",
                "Top Batsman",
                "Top Bowler",
                "Total Wickets",
                "Will There Be Overtime",
                "Total Wides",
                "Team Total Offsides",
                "Will There Be A Century",
                "Will There Be A Safety",
                "Will There Be A Fifty",
                "Will There Be A Tie",
                "Will There Be Extra Innings",
                "Will There Be A Penalty",
                "Team Total Goals",
                "Will There Be A Red Card",
                "Team Total Tackles",
                "Total Aces",
                "Team Total Power Play Goals",
                "Total Cards",
                "Team Total Reg Time",
                "Total Corners",
                "Total Corners Odd/Even",
                "Team Total Rushing Touchdowns",
                "Team Total Rushing Yards",
                "Team Total Rebounds",
                "Team Total Run Outs",
                "Total Behinds",
                "Total Cards Odd/Even",
                "Total Consecutive Points",
                "1st Quarter Player Minutes Played",
                "Race To 50 Points in 2nd Half (Overtime not included)",
                "Combined yardage of made FG's",
                "Distance 1st made FG",
                "Distance of last made FG",
                "Distance of longest enforced penalty in game",
                "Highest scoring quarter will have how many points",
                "Last 6 Minutes Player Points",
                "Longest made FG will be",
                "Longest Touchdown will be how many yards",
                "Lowest scoring quarter will have how many points",
                "Player Shots On Target (Start Or Sub)",
                "Player Shots Total",
                "Player Total Games",
                "Player Total Receptions",
                "Player Total Rush Attempts",
                "Race To 10 Points in 1st Quarter",
                "Race To 10 Points in 2nd Half (Overtime not included)",
                "Race To 10 Points in 2nd Quarter",
                "Race To 10 Points in 3rd Quarter",
                "Race To 10 Points in 4th Quarter (Overtime not included)",
                "Race To 15 Points in 1st Quarter",
                "Race To 15 Points in 2nd Half (Overtime not included)",
                "Race To 15 Points in 2nd Quarter",
                "Race To 15 Points in 3rd Quarter",
                "Race To 15 Points in 4th Quarter (only Points scored in the Quarter/Overtime not included)",
                "Race To 20 Points in 1st Quarter",
                "Race To 20 Points in 2nd Half (Overtime not included)",
                "Race To 20 Points in 2nd Quarter",
                "Race To 20 Points in 3rd Quarter",
                "Race To 20 points in 4th Quarter (only Points scored in the Quarter/Overtime not included)",
                "Race To 25 Points in 1st Half",
                "Race To 25 Points in 1st Quarter",
                "Race To 25 Points in 2nd Half (Overtime not included)",
                "Race To 25 Points in 2nd Quarter",
                "Race To 25 Points in 3rd Quarter",
                "Race To 25 Points in 4th Quarter (only Points scored in the Quarter/Overtime not included)",
                "Race To 30 Points in 1st Half",
                "Race To 30 Points in 1st Quarter",
                "Race To 30 Points in 2nd Half (Overtime not included)",
                "Race To 30 points in 2nd quarter",
                "Race To 30 Points in 3rd Quarter",
                "Race To 30 Points in 4th Quarter (only Points scored in the Quarter/Overtime not included)",
                "Race To 35 Points in 1st Half",
                "Race To 35 Points in 2nd Half (Overtime not included)",
                "Race To 40 Points in 1st Half",
                "Race To 40 Points in 2nd Half (Overtime not included)",
                "Race To 45 Points in 1st Half",
                "Race To 45 Points in 2nd Half (Overtime not included)",
                "Race To 50 Points in 1st Half",
                "Race To 55 Points in 1st Half",
                "Race To 55 Points in 2nd Half (Overtime not included)",
                "Race To 5 Points in 1st Quarter",
                "Race To 5 Points in 2nd Quarter",
                "Race To 5 Points in 3rd Quarter",
                "Race To 5 Points in 4th Quarter (only Points scored in the Quarter/Overtime not included)",
                "Race To 60 Points in 1st Half",
                "Race To 60 Points in 2nd Half (Overtime not included)",
                "Shots on goal by the player - Inc. OT",
                "Super Bowl Coin Toss Result",
                "Super Bowl Gatorade Color",
                "Super Bowl MVP Position",
                "Super Bowl MVP Winner",
                "The largest lead by either team will be",
                "The shortest Touchdown scored in the game will be",
                "Total 4th down conversions by both teams",
                "Total combined yardage of all Touchdowns scored",
                "Total Tie Breaks",
                "Total net yards in the game",
                "Total number of FG's made by both teams",
                "Total number of lost fumbles by both teams",
                "Total number of players to have a passing attempt",
                "Total number of Touchdowns scored in 1st half",
                "Total pass interceptions by both teams",
                "Total punts in the game",
                "Total sacks in the game",
                "Will there be more points scored in",
                "1st 10 Minutes Total Goals",
                "1st 10 Minutes Moneyline",
                "1st 10 Minutes Moneyline 3-Way",
                "1st 10 Minutes Total Cards",
                "1st 10 Minutes Puck Line",
                "1st 2 Innings Player Strikeouts",
                "1st 2 Maps Player Assists",
                "1st 2 Maps Player Creep Score",
                "1st 2 Maps Player Deaths",
                "1st 2 Maps Player Double Kills",
                "1st 2 Maps Player First Blood",
                "1st 2 Maps Player Fantasy Score (Underdog)",
                "1st 2 Maps Player Headshots",
                "1st 2 Maps Player Kills",
                "1st 4 Maps Player Demolitions",
                "1st Half Player Rebounds",
                "1st Half Player Receiving Yards",
                "1st Half Player Rushing Yards",
                "1st Half Player Shots Attempted",
                "1st Half Player Shots",
                "1st Half Point Spread",
                "1st Period Team Total",
                "1st Period Total Goals",
                "1st Period Total Goals Odd/Even",
                "1st Period Total Goals Over/Under",
                "1st Quarter Anytime Touchdown Scorer",
                "1st Quarter First Goal Scorer",
                "1st Quarter Moneyline",
                "2nd Half Player Points + Rebounds + Assists",
                "2nd Half Player Rebounds",
                "2nd Half Point Spread Reg Time",
                "2nd Half Team Total Behinds",
                "2nd Half Team Total Field Goals",
                "2nd Half Team Total Goals",
                "2nd Half Team Total Touchdowns",
                "2nd Half To Score",
                "2nd Map Handicap",
                "2nd Half Team Total Corners",
                "2nd Set Game 10 Winner",
                "2nd Set Game 11 Winner",
                "2nd Set Game 12 Winner",
                "2nd Set Game 1 Winner",
                "2nd Set Game 2 Winner",
                "3rd Set Game 4 Winner",
                "3rd Set Game 5 Winner",
                "3rd Set Game 6 Winner",
                "3rd Set Game 7 Winner",
                "3rd Set Game 8 Winner",
                "3rd Set Game 9 Winner",
                "4th Set Total Games Odd/Even",
                "5th Inning Moneyline",
                "5th Map Moneyline",
                "5th Inning Moneyline 3-Way",
                "5th Inning Run Line",
                "5th Inning To Score",
                "5th Inning Total Hits",
                "5th Inning Total Runs",
                "5th Inning Total Runs Odd/Even",
                "5th Map Asian Handicap",
                "5th Map Handicap",
                "5th Map Player Kills",
                "5th Map Round Handicap",
                "Both Teams To Score",
                "Draw No Bet",
                "Both Teams To Score 2 Goals",
                "Both Players To Win A Set",
                "Cards Handicap",
                "Player Earned Runs",
                "Player Passing + Rushing + Receiving Touchdowns",
                "Player Passing + Rushing Yards",
                "Player Passing Attempts (Combo)",
                "Player Shots Attempted (Start Or Sub)",
                "Coin Toss Result",
                "Gatorade Color",
                "MVP Position",
                "MVP Winner",
                "Player Significant Strikes",
                "To Qualify",
                "Third Goal Scorer",
                "Team Total Shots On Goal",
                "Team Total Sixes",
                "Team Total Touchdowns",
                "Team Total Wides",
                "Team Total Yards",
                "Team Will Score A Century",
                "Team Will Score A Fifty",
                "To Lift The Cup",
                "To Score",
                "To Score A Penalty",
                "To Win The Toss",
                "Total Tiebreaks"
            ],
            max_percentage: "30",
            new_serializer: true,
            page: currentPage,
            sportsbooks: ["bet365", "Ladbrokes (Australia)", "PointsBet (Australia)", "TAB (New Zealand)", "Unibet (Australia)", "TABtouch", "Sportsbet", "Neds"],
            state: "AU-AU"
        };

        const timestamp = Math.floor(Date.now() / 1000);

        try {
            const response = await axios.post(url, payload, {
                headers: {
                    'Content-Type': 'application/json',
                    'Cookie': `${accessToken}`,
                    'Timestamp': timestamp.toString(),
                    'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36',
                    'Signature': generateSignature()
                }
            });

            const pageData = response.data.data || [];
            allData = allData.concat(pageData);

            if (!response.data.has_more) {
                hasMorePages = false;
            } else {
                currentPage++;
            }

        } catch (error) {
            // Handle 401 Unauthorized error with a red embedded message
            if (error.response && error.response.status === 401) {
                await sendDiscordMessage(0xE95046, 'Error: 401 Unauthorized', `Received 401 Unauthorized for page ${currentPage}.`);
                throw error;
            } else {
                await sendDiscordMessage(0xE95046, 'Error Fetching Data', `Error fetching page ${currentPage}: ${error.message}`);
                return null;
            }
        }
    }

    return allData;
}

module.exports = {
  processAllPages
};